# Generated by Django 5.0 on 2023-12-15 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_slug', models.SlugField(blank=True, null=True)),
                ('project_created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('skill_title', models.CharField(max_length=200)),
                ('skill_description', models.TextField()),
                ('skill_created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsTagModel',
            fields=[
                ('tag_title', models.CharField(max_length=200)),
                ('tag_created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
