# Generated by Django 5.0 on 2024-01-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectmodel_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsmodel',
            name='skill_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
