# Generated by Django 5.0 on 2024-01-09 11:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projectmodel_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
