# Generated by Django 5.0 on 2024-01-09 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projectmodel_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('msg_title', models.CharField(max_length=200, null=True)),
                ('msg_email', models.CharField(max_length=200, null=True)),
                ('msg_subject', models.CharField(max_length=200, null=True)),
                ('msg_body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('msg_created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
