# Generated by Django 5.0 on 2024-01-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='msg_id',
        ),
        migrations.RenameField(
            model_name='skillsmodel',
            old_name='id',
            new_name='skill_id',
        ),
        migrations.RenameField(
            model_name='skillstagmodel',
            old_name='id',
            new_name='skill_tag_id',
        ),
    ]
