# Generated by Django 5.0 on 2024-01-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_msg_id_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_subject',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg_title',
            new_name='subject',
        ),
    ]
