# Generated by Django 5.0 on 2024-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(),
        ),
    ]
